apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      initContainers:
      - name: init-storage
        image: alpine:3.18
        command: 
        - "sh"
        - "-c"
        - |
          mkdir -p /tmp/loki/boltdb
          mkdir -p /tmp/loki/chunks
          mkdir -p /tmp/loki/rules
          chmod -R 777 /tmp/loki
        volumeMounts:
        - name: storage
          mountPath: /tmp/loki
        securityContext:
          runAsUser: 0

      containers:
      - name: loki
        image: grafana/loki:2.8.4
        args: ["-config.file=/etc/loki/local-config.yaml"]
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /tmp/loki
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        emptyDir: {}